export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const ORDERS_ROUTE = '/orders'
export const PRODUCT_LIST_ROUTE = '/products'
export const PRODUCT_ROUTE = '/product'
